name: Android U Action

on:
  push:
    branches: [ "Android-U" ]
  pull_request:
    branches: [ "Android-U" ]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - ".idea/"
      - "doc/*"
      - "*.md"
      - ".github/workflows/crowdin.yml"
      - "crowdin.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build App
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: gradle

      - name: Create Sign File
        run: |
          touch signing.properties
          echo storePassword=${{ secrets.KEY_STORE_PASSWORD }} >> signing.properties
          echo keyAlias=${{ secrets.ALIAS }} >> signing.properties
          echo keyPassword='${{ secrets.KEY_STORE_PASSWORD }}' >> signing.properties
          echo storeFile=key.jks >> signing.properties
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > key.jks

      - name: Build with Gradle
        if: contains(github.event.head_commit.message, '[skip]') == false
        shell: bash
        run: ./gradlew assembleCanary

      - name: Find APKs
        if: contains(github.event.head_commit.message, '[skip]') == false
        run: |
          echo "APK_FILE_CANARY=$(find app/build/outputs/apk/canary -name '*.apk')" >> $GITHUB_ENV

      - name: Show APKs SHA256
        if: success() && contains(github.event.head_commit.message, '[skip]') == false
        run: |
          echo "### Build Success" >> $GITHUB_STEP_SUMMARY
          echo "|Artifact|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:--------:|:----------|" >> $GITHUB_STEP_SUMMARY
          canary=($(sha256sum '${{ env.APK_FILE_CANARY }}'))
          echo "|Canary|$canary" >> $GITHUB_STEP_SUMMARY

      - name: Upload Canary APK
        uses: actions/upload-artifact@v3
        with:
          name: Cemiuiler Canary
          path: ${{ env.APK_FILE_CANARY }}

