name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - ".idea/"
      - "doc/*"
      - "*.md"
      - ".github/workflows/crowdin.yml"
      - "crowdin.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build App
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: gradle

      - name: Create Sign File
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          touch signing.properties
          echo storePassword=${{ secrets.KEY_STORE_PASSWORD }} >> signing.properties
          echo keyAlias=${{ secrets.ALIAS }} >> signing.properties
          echo keyPassword='${{ secrets.KEY_STORE_PASSWORD }}' >> signing.properties
          echo storeFile=key.jks >> signing.properties
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > key.jks

      - name: Build with Gradle
        shell: bash
        run: ./gradlew assembleCanary

      - name: Find APKs
        run: |
          zip -r output.zip app/build/outputs/* 

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Cemiuiler Canary
          path: output.zip
